### ISSUE TITLE
强！

### ISSUE THREAD

**Issue by abachelor** [denkywu/Simulation-of-SAR-Imaging-Algorithm#1]
真是大佬呀！请问当时做的RDA,CS的数据还有吗？好像没有传上去，例子想跑，跑不起来

**Comment by denkywu** [comment]
客气了，一点基础的学习而已。另外，不好意思刚看到消息。

rda和cs的详细内容可以参考下 https://github.com/denkywu/SAR-Synthetic-Aperture-Radar/tree/master/1-SAR%E6%88%90%E5%83%8F%E7%AE%97%E6%B3%95 这里面写的，其中就有直接生成的几个点目标的数据并成像。

如果是面目标仿真，比如圆锥场景，平地场景等，可以参考 https://github.com/denkywu/SAR-Synthetic-Aperture-Radar/tree/master/2-InSAR%E5%B9%B2%E6%B6%89SAR-%E4%BA%BA%E9%80%A0%E5%9C%BA%E6%99%AF%E4%BB%BF%E7%9C%9F  这里的，这是为insar仿真做的。不过原理上就是生成了两幅有一定关系的原始数据再做干涉，所以拆出其中一部分就是单个sar的回波数据了。

仅供参考
